INSERT INTO AA_TEST(ID, EMAIL, NAME, REGIST_DATE) VALUES('0000', 'userTest0', 'userName0', SYSDATE);
INSERT INTO AA_TEST(ID, EMAIL, NAME, REGIST_DATE) VALUES('0001', 'userTest1', 'userName1', SYSDATE);
INSERT INTO AA_TEST(ID, EMAIL, NAME, REGIST_DATE) VALUES('0002', 'userTest2', 'userName2', SYSDATE);
INSERT INTO AA_TEST(ID, EMAIL, NAME, REGIST_DATE) VALUES('0003', 'userTest3', 'userName3', SYSDATE);
INSERT INTO AA_TEST(ID, EMAIL, NAME, REGIST_DATE) VALUES('0004', 'userTest4', 'userName4', SYSDATE);
INSERT INTO AA_TEST(ID, EMAIL, NAME, REGIST_DATE) VALUES('0005', 'userTest5', 'userName5', SYSDATE);
INSERT INTO AA_TEST(ID, EMAIL, NAME, REGIST_DATE) VALUES('0006', 'userTest6', 'userName6', SYSDATE);
INSERT INTO AA_TEST(ID, EMAIL, NAME, REGIST_DATE) VALUES('0007', 'userTest7', 'userName7', SYSDATE);
